const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = "Email";
const emailhint = "admin@admin.com";
const password = "password";
const passwordhint = "*****";
const login = "Log in";
const signup = "Sign up";
const forgetpass = "Forget password";
const createNewaccount = "or, create new account";
const loginwith = "Login in with";
const name = "Name";
const retypepassword = "Retype Password";
const termAndCond = "Terms and Conditions ";
const privacyPolicy = " Privacy Policy";
const alreadyHaveAccount = "Already have an account?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchanything = "Search anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash sale",
    brand = "Brand",
    topCategories = "Top Categories",
    featuredCategories = "Featured Categories",
    topsellers = "Top Sellers";
const womendress = "Woman Dress",
    womenwatch = "Women's watch",
    girldress = "Girls dress",
    girlwatches = "Girl Watches",
    boyglasses = "Boy Glasses",
    mobilephone = "Mobile Phone",
    tShirt = "T-shirts";
const featuredproduc = "Featured product";

const womenclothing = "Women Clothing",
    menclothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer and accessories",
    automoble = "automobile",
    kidtoys = "kids & toys",
    sports = "Sports",
    jewllery = "Jewllery",
    cellphone = "Cellphone & Tab",
    furniture = "Furniture";
const addtocart = "Add to Cart";
const seller = "Seller", inhouse = "In house brand";
const video = "Video",
    review = "Review",
    prrivacypolicy = "Privacy and Policy",
    returnpolicy = "Return policy",
    supportpollicy = "Support policy",
    youmayalso = "You may also like";
